var ALIGN = {
	SHORT_CODE : "left",
	LONG_CODE : "left",
	SHORT_STRING : "left",
	LONG_STRING : "left",
	INTEGER : "right",
	LONG : "right",
	DECIMAL : "right",
	DECIMAL_PRECISION : "right",
	DATE : "left",
	TIME : "left",
	DATE_TIME : "left",
	BOOLEAN : "left",
	REFERENCE : "left",
	REFERENCE_LIST : "left",
	IMAGE : "left",
	DOCUMENT : "left",
};
